// stations.js
export const stations = {
  techno: [
    { value: "https://stream.sunshine-live.de/germany/mp3-128", name: "Sunshine Live - German Techno", genre: "Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://stream.sunshine-live.de/technoqueens/aac-64", name: "Sunshine Live - Techno Queens", genre: "Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://online.radiorecord.com.ua/techno", name: "Radio Record - Techno", genre: "Techno", emoji: "⚡", country: "Україна" },
    { value: "https://listen.181fm.com/181-technoclub_64k.aac", name: "181.fm - Techno Club", genre: "Techno", emoji: "⚡", country: "США" },
    { value: "https://stream.sunshine-live.de/techno/mp3-192/radoxo/", name: "Sunshine Live - Techno", genre: "Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://stream.technolovers.fm/big-room", name: "Techno Lovers FM Big Room", genre: "Big Room", emoji: "🎶", country: "Німеччина" },
    { value: "https://stream.technolovers.fm/festivalsounds", name: "Techno Lovers FM Festival Sounds", genre: "Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://stream.laut.fm/cgntechnofm", name: "CGN Techno FM", genre: "Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://streams.radiomast.io/8846a94e-9874-4692-a1a0-ec7aadbe2771", name: "Fnoob Techno", genre: "Techno", emoji: "⚡", country: "США" },
    { value: "https://stream.laut.fm/grooveradio", name: "Groove Radio", genre: "Techno/Minimal", emoji: "🔊", country: "Німеччина" },
    { value: "https://minimalcalling.stream.laut.fm/minimalcalling", name: "Minimal Techno Calling", genre: "Minimal Techno", emoji: "🔊", country: "Німеччина" },
    { value: "https://decoderfm.stream.laut.fm/decoderfm", name: "Decoder FM Radio", genre: "Techno/Minimal", emoji: "🔊", country: "Німеччина" },
    { value: "https://stream.electroradio.fm/192k?icy=https", name: "Electro Radio", genre: "Techno/Electronic", emoji: "🎧", country: "Швейцарія" },
    { value: "https://traxx020.ice.infomaniak.ch/traxx020-low.mp3", name: "Tech Minimal Traxx", genre: "Minimal Techno", emoji: "🔊", country: "Швейцарія" },
    { value: "https://1000techno.stream.laut.fm/1000techno", name: "1000 Techno", genre: "Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://radio.edm1.fm/proxy/17_technique?mp=/stream", name: "edm1.fm - Technique", genre: "Modern Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://radio.edm1.fm/proxy/13_melodia?mp=/stream", name: "edm1.fm - Melodia", genre: "Melodic Techno", emoji: "🎧", country: "Німеччина" },
    { value: "https://www.partyvibe.com:8068/;listen.pls?sid=1", name: "Party Vibe Radio: Techno", genre: "Techno", emoji: "⚡", country: "Велика Британія" },
    { value: "https://cosmo.streamerr.co/proxy/technoradioeuhq/stream", name: "Techno Radio EU", genre: "Techno", emoji: "⚡", country: "Нідерланди" },
    { value: "https://sunsl.streamabc.net/sunsl-melodictechno-mp3-192-4167248", name: "Sunshine Live - Melodic Techno", genre: "Melodic Techno", emoji: "🎧", country: "Німеччина" },
    { value: "https://s2.we4stream.com/listen/loca_techo/live", name: "Loca FM Techno", genre: "Techno", emoji: "⚡", country: "Іспанія" },
    { value: "https://live.radiospinner.com/minimal-techno-96", name: "Minimal Techno", genre: "Techno/Electronic", emoji: "🔊", country: "Іспанія" },
    { value: "https://listen.openstream.co/6521/audio", name: "Minimal & Techno on MixLive.ie", genre: "Dub Techno", emoji: "🔊", country: "Ірландія" },
    { value: "https://live.radiospinner.com/techno-96", name: "Techno", genre: "Techno/Electronic", emoji: "⚡", country: "Іспанія" },
    { value: "https://playerservices.streamtheworld.com/api/livestream-redirect/TOPSPINNING.mp3", name: "TOPspinning 30", genre: "Techno", emoji: "⚡", country: "Бельгія" },
    { value: "https://stream.laut.fm/blockfm", name: "Block FM", genre: "Techno", emoji: "⚡", country: "Швейцарія" },
    { value: "https://stream.laut.fm/crazybass", name: "Crazy Bass", genre: "Techno", emoji: "⚡", country: "Німеччина" },
    { value: "https://stream.laut.fm/darkmindradio", name: "Darkmind Radio", genre: "Melodic Techno", emoji: "🎧", country: "Німеччина" },
    { value: "https://stream.zeno.fm/7ewrk39pknruv", name: "Techno Importation", genre: "Techno", emoji: "⚡", country: "Франція" }
  ],
  trance: [
    { value: "https://stream.sunshine-live.de/trance/mp3-192/radoxo/", name: "Sunshine Live - Trance", genre: "Trance", emoji: "🎶", country: "Німеччина" },
    { value: "https://listen.trancebase.fm/tunein-mp3", name: "TRANCEBASE.FM", genre: "Trance/Techno", emoji: "🎶", country: "Німеччина" },
    { value: "https://radio.trance-energy.org:8443/trance", name: "Trance-Energy Radio", genre: "Trance/Techno", emoji: "🎶", country: "Нідерланди" },
    { value: "https://stream.technolovers.fm/vocal-trance", name: "Techno Lovers FM Vocal Trance", genre: "Vocal Trance", emoji: "🎶", country: "Німеччина" },
    { value: "https://s2.radioparty.pl:8025/vocaltrance", name: "Radioparty - Vocal Trance", genre: "Vocal Trance", emoji: "🎶", country: "Польща" },
    { value: "https://stream.laut.fm/ganorium-radio", name: "Ganorium Radio", genre: "Vocal Progressive", emoji: "🎶", country: "Німеччина" },
    { value: "https://icecast.pulsradio.com/pulsHD.mp3", name: "PulsRadio Dance", genre: "Trance/Techno", emoji: "🎧", country: "Франція" },
    { value: "https://sunsl.streamabc.net/sunsl-newhits-mp3-192-1294829", name: "Sunshine Live - New Music", genre: "Techno/Trance", emoji: "🎶", country: "Німеччина" },
    { value: "https://streaming.playtrance.com/playtrance-main-low", name: "Play Trance - Main Channel", genre: "Trance", emoji: "🎶", country: "Іспанія" },
    { value: "https://live-ff.playtrance.com/playtrance-classics.mp3", name: "PlayTrance Radio (Classics Channel)", genre: "Trance", emoji: "🎶", country: "Іспанія" },
    { value: "https://london-dedicated.myautodj.com:3199/proxy/trance/stream", name: "Toronto Global Radio", genre: "Trance", emoji: "🎶", country: "Канада" },
    { value: "https://server35920.streamplus.de/stream.mp3", name: "Trance Motion FM", genre: "Trance", emoji: "🎶", country: "Німеччина" },
    { value: "https://live.radiospinner.com/vcltrnc-96", name: "Vocal Trance", genre: "Trance/Electronic", emoji: "🎶", country: "Іспанія" },
    { value: "https://strmreg.1.fm/trance_mobile_mp3", name: "1.FM - Absolute Trance Radio", genre: "Trance/Dance", emoji: "🎶", country: "Швейцарія" },
    { value: "https://online.kissfm.ua/KissFM", name: "Kiss FM Ukraine", genre: "Dance/Electronic", emoji: "🎧", country: "Україна" },
    { value: "https://cast.brg.ua/djfm_main_public_mp3_hq", name: "DJFM", genre: "EDM/Techno", emoji: "🎧", country: "Україна" },
    { value: "https://secure.live-streams.nl/live", name: "Intense Radio", genre: "House/Techno/Trance", emoji: "🎧", country: "Нідерланди" }
  ],
  ukraine: [
    { value: "https://online.kissfm.ua/KissFM", name: "Kiss FM", genre: "Танцювальна музика", emoji: "💃", country: "Україна" },
    { value: "https://cast.brg.ua/djfm_main_public_mp3_hq", name: "DJ FM", genre: "Танцювальна/EDM", emoji: "💃", country: "Україна" },
    { value: "https://online.hitfm.ua/HitFM", name: "Хіт FM", genre: "Поп-музика", emoji: "🎶", country: "Україна" },
    { value: "https://icecast.luxnet.ua/lux_mp3", name: "Люкс ФМ", genre: "Поп-музика", emoji: "🎶", country: "Україна" },
    { value: "https://cast.mediaonline.net.ua/radiopyatnica320", name: "Радіо П’ятниця", genre: "Поп-музика", emoji: "🎶", country: "Україна" },
    { value: "https://online.radioroks.ua/RadioROKS", name: "Radio ROKS", genre: "Рок-музика", emoji: "🎸", country: "Україна" },
    { value: "https://online.radiorelax.ua/RadioRelax", name: "Radio Relax", genre: "Легка музика", emoji: "🌿", country: "Україна" },
    { value: "https://online.melodiafm.ua/MelodiaFM", name: "Мелодія FM", genre: "Поп/Романтична музика", emoji: "🎵", country: "Україна" },
    { value: "https://online.nasheradio.ua/NasheRadio", name: "Наше Радіо", genre: "Поп/Рок", emoji: "🎶", country: "Україна" },
    { value: "https://icecast.luxnet.ua/maximum_mp3", name: "Радіо МАКСИМУМ", genre: "Поп/Рок", emoji: "🎸", country: "Україна" },
    { value: "https://icecast.luxnet.ua/nostalgie_mp3", name: "Radio NOSTALGIE", genre: "Ретро", emoji: "🎤", country: "Україна" },
    { value: "https://online.radiojazz.ua/RadioJazz", name: "Radio Jazz", genre: "Джаз", emoji: "🎷", country: "Україна" },
    { value: "https://online.classicradio.ua/ClassicRadio", name: "Classic Radio", genre: "Класична музика", emoji: "🎻", country: "Україна" },
    { value: "https://cast.brg.ua/shanson_main_public_mp3_hq", name: "Шлягер FM", genre: "Шансон/Естрада", emoji: "🎙", country: "Україна" },
    { value: "https://cast.brg.ua/powerfm_main_public_mp3_hq", name: "Power FM", genre: "Поп/Танцювальна", emoji: "🎧", country: "Україна" },
    { value: "https://cast.brg.ua/business_main_public_mp3_hq", name: "Magic Radio", genre: "Легка музика", emoji: "🌿", country: "Україна" },
    { value: "https://cast.mediaonline.net.ua/avtoradio320", name: "Авторадіо", genre: "Поп-музика", emoji: "🚗", country: "Україна" },
    { value: "https://online.radiobayraktar.ua/RadioBayraktar", name: "Радіо БАЙРАКТАР", genre: "Українська музика", emoji: "🇺🇦", country: "Україна" },
    { value: "https://stream320.galychyna.fm/RadioPlayer", name: "FM Галичина", genre: "Українська музика", emoji: "🇺🇦", country: "Україна" },
    { value: "https://onair.lviv.fm:8443/lviv.fm", name: "Львівська Хвиля", genre: "Поп/Українська музика", emoji: "🎶", country: "Україна" },
    { value: "https://icecast.luxnet.ua/luxlviv_mp3_320", name: "Люкс ФМ (Львів)", genre: "Поп-музика", emoji: "🎶", country: "Україна" },
    { value: "https://ipradio.net:8443/duzheHD", name: "Дуже Радіо", genre: "Українська музика", emoji: "🇺🇦", country: "Україна" },
    { value: "https://live.radio1.com.ua/liveradio320", name: "Радіо ПЕРШЕ", genre: "Поп-музика", emoji: "🎶", country: "Україна" },
    { value: "https://audio.radiotrek.rv.ua/", name: "Радіо Трек", genre: "Поп/Рок", emoji: "🎸", country: "Україна" },
    { value: "https://cdn-br2.live-tv.cloud/sferarvFM/320k/icecast.audio", name: "Сфера-ФМ", genre: "Поп-музика", emoji: "🎶", country: "Україна" },
    { value: "https://online.1043.com.ua/1043fm", name: "Західний Полюс", genre: "Поп/Рок", emoji: "🎸", country: "Україна" },
    { value: "https://100.cv.ua:8443/play", name: "Буковинська Хвиля", genre: "Поп/Народна музика", emoji: "🎶", country: "Україна" },
    { value: "https://stream.chv.ua:8443/acc.mp3", name: "Радіо 10", genre: "Поп-музика", emoji: "🎶", country: "Україна" },
    { value: "https://radio.c4.com.ua:8443/320", name: "Радіо C4", genre: "Поп-музика", emoji: "🎶", country: "Україна" }
  ],
  pop: [
    { value: "https://ice-sov.musicradio.com/CapitalBirminghamMP3", name: "Capital FM", genre: "Pop", emoji: "🎶", country: "Велика Британія" },
    { value: "https://stream.revma.ihrhls.com/zc1961", name: "Z 100 Portland", genre: "Pop", emoji: "🎶", country: "США" },
    { value: "https://freedomice.streamakaci.com/cheriefm1.mp3", name: "Chérie FM", genre: "Pop/Top 40", emoji: "🎶", country: "Франція" },
    { value: "https://stream.rfm.fr/rfm.mp3", name: "RFM", genre: "Pop", emoji: "🎶", country: "Франція" },
    { value: "https://secureonair.krone.at/kronehit1058.mp3", name: "Kronehit", genre: "Pop", emoji: "🎶", country: "Австрія" },
    { value: "https://streams.egofm.de/egoFMSAX-hq", name: "Ego FM", genre: "Pop", emoji: "🎶", country: "Німеччина" },
    { value: "https://topfm-live.cast.addradio.de/topfm/live/mp3/high", name: "Top FM Germany", genre: "Pop/Rock", emoji: "🎸", country: "Німеччина" },
    { value: "https://sc.creacast.com/topmusic_haguenau", name: "Top Music", genre: "Pop/Rock", emoji: "🎸", country: "Франція" },
    { value: "https://live-bauerno.sharp-stream.com/top40_no_mp3", name: "Topp 40 Norway", genre: "Pop", emoji: "🎶", country: "Норвегія" },
    { value: "https://wz7liw.scahw.com.au/live/7top30_128.stream/playlist.m3u8", name: "Top 30 Australia", genre: "Pop", emoji: "🎶", country: "Австралія" },
    { value: "https://stream.laut.fm/top100germany", name: "Top 100 Germany", genre: "Pop/Charts", emoji: "🎶", country: "Німеччина" },
    { value: "https://stream.laut.fm/top100-worldwide", name: "Top 100 Worldwide", genre: "Pop/Charts", emoji: "🎶", country: "Німеччина" },
    { value: "https://stream.laut.fm/top4you", name: "Top 4 You", genre: "Pop/Charts", emoji: "🎶", country: "Німеччина" },
    { value: "https://boxradio-edge-03.streamafrica.net/pop", name: "Pop", genre: "Pop", emoji: "🎶", country: "Велика Британія" },
    { value: "https://stream.revma.ihrhls.com/zc8470", name: "Po P 99.1 Hawaii", genre: "Pop", emoji: "🎶", country: "США" },
    { value: "https://pophits128-thehitsnetwork.radioca.st/http/pollux.shoutca.st:8939/1", name: "Pop Hits Radio", genre: "Pop", emoji: "🎶", country: "Велика Британія" },
    { value: "https://streaming.live365.com/a36628", name: "Pop Across The Pond", genre: "Pop/Alternative", emoji: "🎶", country: "США" },
    { value: "http://pollux.shoutca.st:8939/stream2", name: "Pop Hits", genre: "Pop", emoji: "🎶", country: "Велика Британія" },
    { value: "https://main-high.rautemusik.fm/stream.mp3", name: "Pop-Radio", genre: "Pop/Top 40", emoji: "🎶", country: "Німеччина" },
    { value: "https://stream1.xdevel.com/audio4s975552-212/stream/icecast.audio", name: "Radio Bruno", genre: "Pop", emoji: "🎶", country: "Італія" },
    { value: "https://ice18.fluidstream.net/area05.mp3", name: "Radio Number One", genre: "Pop", emoji: "🎶", country: "Італія" },
    { value: "https://edge-bauerall-01-gos2.sharp-stream.com/kisstory.aac", name: "Kisstory", genre: "Pop/House", emoji: "🎶", country: "Велика Британія" },
    { value: "https://energybasel.mp3.energy.ch/energybasel-high.mp3", name: "Energy", genre: "Pop", emoji: "🎶", country: "Швейцарія" },
    { value: "https://chmedia.streamabc.net/79-argovia-mp3-192-3024993", name: "Radio Argovia - Pop", genre: "Pop/Rock", emoji: "🎸", country: "Швейцарія" },
    { value: "https://rhema-radio.streamguys1.com/rhema-lifefm.aac", name: "Life FM", genre: "Christian Pop", emoji: "🎶", country: "Нова Зеландія" },
    { value: "https://mdr-991101-0.sslcast.mdr.de/mdr/991101/0/mp3/low/stream.mp3", name: "MDR Tweens", genre: "Pop", emoji: "🎶", country: "Німеччина" },
    { value: "https://100radio-tarbes.ice.infomaniak.ch/100radio-tarbes-128.mp3", name: "100% Radio", genre: "Pop", emoji: "🎶", country: "Франція" },
    { value: "https://play.global.audio/nrj128", name: "Radio Energy", genre: "Pop", emoji: "🎶", country: "Болгарія" },
    { value: "https://kisskiss.fluidstream.eu/KKNapoli.mp3?FLID=8&type=.mp3", name: "Radio Kiss Kiss Napoli", genre: "Italo-Pop", emoji: "🎶", country: "Італія" },
    { value: "https://edge-audio-06-cr.sharp-stream.com/ssvcbfbs2.mp3", name: "Bfbs Radio 2", genre: "Pop", emoji: "🎶", country: "Велика Британія" },
    { value: "https://edge-bauerall-01-gos2.sharp-stream.com/gem106.aac", name: "Gem FM", genre: "Pop", emoji: "🎶", country: "Велика Британія" },
    { value: "https://ice.abradio.cz/orion128.aac", name: "Hitrádio Orion", genre: "Pop", emoji: "🎶", country: "Чехія" }
  ]
};